[package]
name = "file_url"
version = "0.1.0"
authors = ["Jared Smith <jasmith79@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlencoding = "2.1.0"
regex = "1.3.6"
lazy_static = "1.4.0"
